project:
  type: website
  output-dir: docs

website:
  title: "Curriculum for Urban Injury Research and Epidemiology (CURE)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - bayes.qmd

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true



