project:
  type: website
  output-dir: docs

website:
  title: "CUIRE"
  navbar:
    left:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - sidebar:bayes
      - sidebar:epidemiology
      - rCourse.qmd
      - spatialEpi.qmd

  sidebar:
    - id: bayes
      title: "Bayes"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
          - bayes/bayes1/bayes1.qmd
          - bayes/bayes2/bayes2.qmd
          - bayes/bayes3/bayes3.qmd
          - bayes/bayes4/bayes4.qmd
          - bayes/bayes5/bayes5.qmd

    - id: epidemiology
      title: "Epidemiology"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
          - epidemiology/introEpi.qmd
          - epidemiology/injuryDisaster.qmd
          - epidemiology/power.qmd
          - epidemiology/prob.qmd

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true



