---
title: "Who I am, and what I do."
---


I'm an [injury epidemiologist](https://med.nyu.edu/faculty/charles-j-dimaggio).  Some of my NIH and CDC-funded work includes describing and analyzing the epidemiology of pediatric pedestrian injuries and the effectiveness of the national Safe Routes to School Program, conducting surveillance to track and explain the behavioral health effects of the terrorist attacks of September 11th, 2001 in New York, and investigating the developmental and behavioral effects of anesthesia on young children. I've worked on a variety of public-health related issues including bioterrorism preparedness, syndromic surveillance, and health disparities, and have an active and abiding interest in the epidemiological application of Bayesian and spatial models to population health, and large data sets. I teach classes, workshops and training sessions on both introductory and advanced methods using the R programming languages. I previously developed and taught an introductory course on the use of SAS for epidemiologists that resulted in a [textbook](https://link.springer.com/book/10.1007/978-1-4614-4854-9). I'm currently Professor of Surgery and Population Health at New York University School of Medicine in the division of trauma and critical care. I hold an adjunct position in the department of epidemiology at Columbia's Mailman School of Public Health where I spent two decades as associate professor of anesthesiology and epidemiology. My prior experience also  includes research director for the Columbia Center for Injury Epidemiology and Control, research scientist with the Nassau County, NY, Department of Health, and nearly two decades as chief physician assistant and director of research for the emergency department at Mt. Sinai School of Medicine at Elmhurst Hospital Center in New York City. You can find links to published versions of my papers at my Columbia University [academic commons](https://academiccommons.columbia.edu/search?search_field=all_fields&q=Charles+DiMaggio) search site, on the  New York University Health Sciences Library system [faculty bibliography page](https://library.med.nyu.edu/api/publications?person=dimagc01) as well as within this site itself.

Following are links to some media references to my work over the years.


# Pediatric Pedestrian Injury

I have spent a the majority of my recent research effort trying to determine if the Safe Routes to School (SRTS) program prevents pediatric pedestrian injury. This nationwide, federally-funded, locally-administered transportation initiative of safety improvements to the built environment surrounding schools is intended to encourage active travel to and from school. As of 2012, departments of transportation in all 50 states, and the District of Columbia, had introduced safety improvements at 10,400 of the nation's 98,706 elementary and secondary schools for a total cost of $1.12 billion, and nearly half of all available funds had been allocated for projects. While a number of studies have assessed programmatic aspects of SRTS programs and evaluated their impact on children's physical activity, little is known about the effectiveness of the SRTS program in reducing pedestrian injury risk in school-age children.  While motivated primarily as an obesity prevention program, I have lead a number of comprehensive, opportunistic, detailed evaluations of the public health impact of what is essentially the largest single investment in a pediatric injury prevention program in United States history. My colleagues and I have documented the safety benefit the SRTS program in New York City by demonstrating a nearly 44% pre-post SRTS implementation decline in school-age school-travel pedestrian injuries at SRTS schools compared to essentially no change in non-SRTS areas.  We extended this analysis to cost effective analyses to demonstrate a net societal benefit of $230 million and 2,055 quality adjusted life years gained in New York City as a result of the SRTS program. This was followed by the translation of advanced spatiotemporal modeling methods to all-age NYC pedestrian injury data, to demonstrate the utility of advanced epidemiologic methods for pedestrian injury control research in support of the city's Vision Zero efforts. In a study recently accepted for publication in Injury Epidemiology, we demonstrated similar injury control benefits in a statewide analysis of Texas pedestrian crash data. In addition to peer-reviewed scientific literature, this research has been the subject of considerable media attention including published reports in print, radio and television media over the last year, including [Reuters](https://www.reuters.com/article/idUSBRE90D07E20130114/?irpc=932),  [US News and World Report](http://health.usnews.com/health-news/news/articles/2013/01/14/safer-roads-near-schools-may-mean-fewer-kids-struck-by-cars), [local](https://www.ksgf.com/2026/03/29/electric-bikes-can-be-fast-and-dangerous-heres-how-to-stay-safe/) and [national](https://abcnews.com/GMA/Family/parents-file-lawsuit-bike-company-daughters-death/story?id=88002829) television news outlets,  [WNYC radio](https://wnyc.org/story/316482-school-kids-and-cars-nyc/),  the [Gotham Gazette](https://www.gothamgazette.com/government/5380-kid-un-friendly-streets-child-pedestrian-deaths-injuries-vision-zero-new-york-city/),  [Scientific American](https://www.scientificamerican.com/blog/observations/pedestrian-safety/),  [Fox News](https://www.foxnews.com/health/pedestrian-safety-program-prevents-student-injuries), and [letters](https://www.nytimes.com/2013/03/07/opinion/saving-childrens-lives.html?_r=0), [opinions](https://www.nytimes.com/2018/10/05/opinion/letters/subways-new-york-city.html) and [interviews](https://www.nytimes.com/2026/08/08/well/pedestrian-deaths-car-collision-older.html) in the New York Times.


# Mass Shootings, E-bikes, and COVID

I have been fortunate to pursue varied work with colleagues at Columbia University and in the department of surgery division of truma at NYU / Bellevue. The following media links highlight some of that activity.


Several years ago my colleagues and I in the division of trauma and surgical critical care reported our analysis of the effect of the US Assault Weapons Ban of the 1990s. While not everyone agreed with or accepted our conclusions, it stirred a fair amount of discussion and debate on [CBS Evening News](https://www.cbs.com/shows/video/BIdzE2Pqy_r6_dAaTqASsHVTT0YozS7O/), in [Popular Science Magazine](https://www.popsci.com/health/gun-violence-kids-mental-health/), in the [Washington Post](https://www.washingtonpost.com/politics/2022/05/27/what-research-shows-effectiveness-gun-control-laws/) at least [twice](https://www.washingtonpost.com/politics/2021/03/24/bidens-claim-that-1994-assault-weapons-law-brought-down-mass-shootings/), on [CNN](https://www.cnn.com/2022/05/26/politics/gun-violence-data-what-matters/index.html), on [Politifact](https://www.politifact.com/factchecks/2022/may/25/joe-biden/joe-biden-said-mass-shootings-tripled-when-assault/), on [NPR](https://whyy.org/npr_story_post/biden-wants-new-ban-on-assault-style-weapons-what-lessons-were-learned-from-the-90s/), and in the [Texas Tribune](https://www.texastribune.org/2022/06/06/texas-uvalde-gun-policy/)



E-bikes and motorized micromobility are emerging issues in injury epidemiology. Some of the work I conducted with my clinical colleagues has attracted attention. [E-bike head trauma soars](https://www.npr.org/sections/health-shots/2024/02/21/1232912369/e-bike-head-trauma-soars-as-helmet-use-falls-study-finds) as helmet use falls, study finds. [Fortune Magazine](https://fortune.com/2023/06/01/e-bike-injuries-trauma-experts-warn-numbers-health-carolyn-barber/) Report: "E-bike injuries: Trauma experts warn ‘we’re only seeing the tip of the iceberg". [Good Morning America](https://abcnews.go.com/GMA/News/video/parents-file-lawsuit-bike-manufacturer-daughters-death-88033371) interview:  "Parents file lawsuit against e-bike manufacturer following daughter's death". [New York Times](https://www.nytimes.com/2022/08/01/style/team-molly-rad-power-bikes-lawsuit.html?smid=fb-nytimes&smtyp=cur&fbclid=IwAR0b-6O3p8IpaYRfR4-WQqwm4iArVyuMY6x4Yg-1Qfd1NcjbD-lFDOYh6IM&fs=e&s=cl). interview:  "‘Team Molly’ Parents Sue E-Bike Company Over Daughter’s Death".  "Is an E-Bike Right for You?  What you need to know about choosing an electric bicycle",  [Consumer Reports](https://www.consumerreports.org/electric-bikes/is-an-e-bike-right-for-you-electric-bike-buying-guide/),  1 July 2021. "Simon Cowell injured in e bike accident",  [ABC News](https://www.youtube.com/watch?v=hOph9ciw7jw), 10 August 2020.  "Simon Cowell recovering from surgery after electric bike accident", [NBC News](https://www.nbcnews.com/nightly-news/video/simon-cowell-recovering-from-surgery-after-electric-bike-accident-89823813644?mc_cid=ad6224b337&mc_eid=[cfa854ac40]), 9 August 2020. "E-Bikes Are All the Rage. Should They Be?", [New York Times](https://www.nytimes.com/2020/08/19/well/move/e-bike-safety-exercise.html?mc_cid=ad6224b337&mc_eid=[cfa854ac40]),  19 August 2020. 



During the COVID19 Pandemic, our focus (and that of most epidemiologists) pivoted toward studying how to prevent and control the spread of disease. "Why Is the Delta Variant More Contagious, Should the Vaccinated Worry? Doctors Explain" [Newsweek](https://www.newsweek.com/why-delta-variant-more-contagious-should-vaccinated-worry-doctors-explain-1614291). 29 July 2021. 
"New Yorks erfolgreicher Kampf gegen die Pocken (New York's successful fight against smallpox)", [ARD German Public Broadcasting](https://www.tagesschau.de/ausland/amerika/newyork-pocken-impfung-101.html), 10 February 2021.  "Taking Lessons From Smallpox to Learn How to Vaccinate an Entire City",  [NBC News](https://www.nbcnewyork.com/news/taking-lessons-from-smallpox-to-learn-how-to-vaccinate-an-entire-city/2827594/), 13 January 2021  "How New York City Vaccinated 6 Million People in Less Than a Month",  [New York Times](https://www.nytimes.com/2020/12/18/nyregion/nyc-smallpox-vaccine.html?referringSource=articleShare), 18 December 2020.  "Rural Americans, Once 8 Times Less Likely to Die From COVID, Now Nearly 2.5 Times More Likely",  [Newsweek](https://www.newsweek.com/rural-americans-once-8-times-less-likely-die-covid-now-nearly-25-times-more-likely-1547851), 16 November 2020.  "3 Cities Saw COVID Cases Increase By Triple Digits Over 8 Weeks Despite Mask Mandates", [Newsweek](https://www.newsweek.com/3-cities-saw-covid-cases-increase-triple-digits-over-8-weeks-despite-mask-mandates-1548877), 20 November 2020. 
  


# Anesthesia and Pediatric Neurodevelopment



As part of my appointment in the department of anesthesiology at the Columbia University Medical Center, my colleagues and I investigated the potential role of early exposure to anesthesia in neurodevelopmental disorders. Recent animal studies have shown that commonly used anesthetic agents may have serious neurotoxic effects on the developing brain. My work to assess the association between surgery for hernia repair and the risk of behavioral and developmental disorders in young children was among the first and most highly cited clinical research on this topic. We performed a retrospective cohort analysis of children who were enrollees of the New York State Medicaid program. Our analysis involved following a birth cohort of 383 children who underwent inguinal hernia repair during the first three years of life, and a sample of 5050 children frequency-matched on age with no history of hernia-repair before age 3. After controlling for age, gender, and complicating birth-related conditions such as low birth weight, children who underwent hernia repair under three years of age were more than twice as likely as children in the comparison group to be subsequently diagnosed with a developmental or behavioral disorder (adjusted HR 2.3, 95% CI 1.3, 4.1). Our findings add to recent evidence of the potential association of surgery and its concurrent exposure to anesthetic agents with neurotoxicity and underscore the need for more rigorous clinical research on the long-term effects of surgery and anesthesia in children. More recently, we looked at the same question using a twin sibling cohort, finding attenuated but similar results. Some of the results of this work have been featured on [Science Daily](https://www.sciencedaily.com/releases/2010/10/101018163301.htm),  CNN,  [US News and World Report](http://health.usnews.com/health-news/news/articles/2012/08/20/anesthesia-before-age-3-may-raise-risk-of-learning-delays-study), and [ABC](https://abcnews.com/Health/Healthday/story?id=6082996&page=1) news.





# Disaster Preparedness and Response

Injuries and disasters exact an enormous toll on population health and well-being. In the aftermath of the terrorist attacks of September 11, 2001, I joined with other public health practitioners and epidemiologists to contribute to controlling and preventing the physical and social consequences of disasters by collecting, analyzing and interpreting data to help guide control and preparedness efforts. As population health scientists we were challenged to more broadly define injuries to include behavioral and mental health outcomes, utilize non-traditional and forward-thinking research methods, and structure innovative control and treatment programs based on evidence. This early work continues to inform my research and approach to public health. You can find links to disaster-related educational material and published reports on this site.

















