---
title: "Disaster Code and Abstracts"
---

# Disasters

## Selected Disaster-Related Papers

### The Terrorist Attacks of September 11, 2001 in New York City

Funded in large part by the US Centers for Disease Control and Prevention, the following papers describe and analyze the effects of the terrorist attacks of September 11, 2001 on the residents of New York City.

In this 2006 [meta-analysis](https://academiccommons.columbia.edu/doi/10.7916/D89W0N7S), I attempted to synthesize what is known about the behavioral health effects of terrorism. The United States Department of State has documented 228 acts of worldwide terrorism between 1961 and 2003. Of these 197 were in the developing world. In the US, attention has turned to the threat of terrorism with the September 11, 2001 terrorist bombings, the largest single-day loss of human-life in US history since the Civil War. Subsequent terrorist attacks such as the October 12, 2002 Bali nightclub bombings, the March 11, 2004 Madrid train bombings, and the July 7, 2005 London bombings, have further brought the threat of terrorism to the forefront of national and international discourse. Several large-scale reviews of the consequences of disasters have been published. These reviews have documented the prevalence and correlates of specific psychiatric disorders and behaviors after mass events. Post-traumatic stress disorder (PTSD) emerges from this work as the best studied, and likely most common, psychopathology after disasters. One theme to arise from these reviews is that disasters that are caused by human-intent (such as terrorism) may be associated with a particularly high risk of psychopathology in their aftermath. To illuminate this issue, we undertook a review and synthesis of quantitative studies of the behavioral health effects of terrorist incidents focusing primarily on the prevalence and correlates of PTSD.

In this [textbook chapter](https://academiccommons.columbia.edu/doi/10.7916/D8WQ09J7) we reviewed the available evidence about the mental health and behavioral consequences of terrorism, considered methodological and research issues that challenge the field, and discussed the evidence for specific prevention and treatment efforts aimed at mitigating the mental health and behavioral consequences of terrorism. In this more recent textbook chapter, we focussed on the events of September 11, 2001 in New York City.

In this review article we focused on the [clinical implications](https://academiccommons.columbia.edu/doi/10.7916/D8SX6M06) of terrorist-related behavioral health disorders. Emergency physicians are likely to be first-line responders in any local or regional terrorist event. In addition to preparing for the potential physical conditions and injuries that are associated with terrorism, they should be aware of the behavioral and mental health implications as well. It is helpful to be familiar with the characteristics that predict who may be at increased risk for mental illness after such events and how they may be identified in an Emergency Department setting. Although most people in the general population with behavioral conditions stemming from a terrorist event can be expected to recover spontaneously within several months, other individuals are at increased risk of developing more debilitating mental health conditions that have been associated with post-terrorist and disaster environments. Screening tools are available to help emergency practitioners identify them and refer patients for more formal psychiatric evaluation and potential interventions to facilitate and speed the recovery process.

After writing up some initial reviews, we conducted a series of more analytic studies.

To illustrate how spatial modeling methods may provide insight about the relation between [proximity to mass trauma and substance use](https://academiccommons.columbia.edu/doi/10.7916/D8542VBJ), we examined the role of proximity to a terrorist event in determining risk of substance use-related diagnoses. Previous analyses that have assessed changes in substance use following mass traumas such as terrorist attacks have produced conflicting results. We used Bayesian hierarchical modeling methods to assess whether distance from the World Trade Center (WTC) site in the aftermath of the September 11, 2001 terrorist attacks was associated with risk of substance use-related diagnoses. In analyses controlling for age, gender, median household income and employment-related exposure to the terrorist attacks, we found that each two mile increment in distance away from the World Trade Center site was associated with 18% more substance use-related diagnoses in the population we studied; this relation between distance from the WTC and substance use-related disorder was the opposite of the relations observed one year before the same attacks in the same area. By accounting for spatial relationships that may influence the population risk of substance use health disorder, this approach helps explain some of the conflicting observations in the extant literature. These methods hold promise for the characterization of disease risk where spatial patterning of exposures and outcomes may matter.

While several population-based studies documented behavioral health disturbances following terrorist attacks, a number of mental health service utilization analyses presented conflicting conclusions. We tried to determine if mental health service utilization increased following a terrorist attack by assessing [changes in psychoactive drug prescription rates](https://academiccommons.columbia.edu/doi/10.7916/D87W6JX5). We measured the rate of selective serotonin reuptake inhibitor (SSRI) prescriptions among New York State Medicaid enrollees before and after the terrorist attacks of September 11, 2001, and assessed the association between geographic proximity to the events and changes in the rate of SSRI prescriptions around September 11, 2001 We found that from September to December 2001, among individuals residing within 3 miles of the WTC site, there was an 18.2% increase in the SSRI prescription rate compared to the previous 8 month period (p=0.0011). While there was a 9.3% increase for non-New York City residents, this change was not statistically significant (p=0.74). We concluded that there was a quantifiable increase in the dispensing of psychoactive drugs following the terrorist attacks of September 11, 2001 and that this effect varied in response to geographic proximity to the events. These findings build on the growing body of knowledge on the pervasive effects of disasters and terrorist events for population health and demonstrate the need to include mental and behavioral health as key components of surge capacity and public health response to mass traumas. We presented a shorter version of this material here.

We also looked at population-level psychiatric disturbances spatially. We wanted to assess the appropriateness of using Bayesian hierarchical spatial techniques to answer the question of the role of [proximity to a mass trauma as a risk factor for psychopathology](https://academiccommons.columbia.edu/doi/10.7916/D8DN4BS8). Using a set of individual-level Medicaid data for New York State, and controlling for age, gender, median household income and employment-related exposures, we applied Bayesian hierarchical modeling methods for spatially aggregated data. We found that distance from the World Trade Center site in the post-attack time period was associated with increased risk of anxiety-related diagnoses. In the months following the attack, each 2-mile increment in distance closer to the World Trade Center site was associated with a 7% increase in anxiety-related diagnoses in the population. No similar association was found during a similar time period in the year prior to the attack. We conclude that spatial variables help more fully describe post-terrorism psychiatric risk and may help explain discrepancies in the existing literature about these attacks. These methods hold promise for the characterization of disease risk where spatial patterning of ecologic-level exposures and outcomes merits consideration.

We looked closely at the [role of emergency departments](https://academiccommons.columbia.edu/doi/10.7916/D8639WFX) in providing behavioral and psychiatric health care following the terrorist attacks of September 11, 2001. We assessed presentations to emergency departments using Medicaid analytic extract files for adult New York State residents for 2000 and 2001. We created four mutually exclusive geographic areas that were progressively more distant from the World Trade Center and divided data into 4 time periods. All persons in the files were categorized by their zip code of residence. We coded primary emergency department diagnoses for post traumatic stress disorder, substance abuse, psychogenic illness, severe psychiatric illness, depression, sleep disorders, eating disorders, stress-related disorders, and adjustment disorders. There was a 10.1% relative temporal increase in the rate of emergency department behavioral and mental health diagnoses following the September 11, 2001 terrorist attacks for adult Medicaid enrollees residing within a 3-mile radius of the World Trade Center site. Other geographic areas experienced relative declines. In population-based comparisons, Medicaid recipients, who lived within 3 miles of the World Trade Center following the September 11, 2001 terrorist attacks had a 20% increased risk of an emergency department mental health diagnosis (Prevalence Density Ratio 1.2, 95% CI 1.1, 1.3) compared to those who were non-New York City residents. The complex role that emergency departments may play in responding to terrorism and disasters is becoming increasingly apparent. To the best of our knowledge this is the first report of a quantifiable increase in emergency department utilization for mental health services by persons exposed to a terrorist attack in the United States.

Finally, we looked at [how academic institutions and public health agencies can partner to prepare](https://academiccommons.columbia.edu/doi/10.7916/D8JD53JF) for and respond to terrorism and disasters. The New York City Department of Health and Mental Hygiene and the Columbia University Mailman School of Public Health's National Center for Disaster Preparedness undertook a collaborative project to establish a model academic health department. The goals were to increase student participation at the health department, increase faculty participation in health department activities, and facilitate health department faculty appointments at the school. As a result, 17 students were placed in full-time summer research projects designed by health department staff specifically for the project, 154 health department staff attended a series of six lectures presented by faculty, and five health department professionals applied for academic appointments at the school. The benefits of the efforts toward establishing an academic health department extend to all areas of public health practice, including those of preparedness.

### Mapping COVID19 Testing Results in New York City

At the height of the COVID19 pandemic in New York City, we [analyzed positive COVID-19](https://pubmed.ncbi.nlm.nih.gov/32827672/) testing results counts within New York City ZIP Code Tabulation Areas with Bayesian hierarchical Poisson spatial models using integrated nested Laplace approximations. We found that spatial clustering explained 32% of data variation, with higher test positivity linked heavily to Black/African American race, older age, and underlying conditions.



## Selected Code for Disaster-Related Analyses


[Mapping Hurricane Sandy](/resources/useRslides.pdf) damage. UseR! conference University of Castilla-La Mancha, Alcacetes Spain, July 2012.

[Code for Bayesian Hierarchical Spatial Modeling](/resources/covidINLA.html) of New York City ZIP Code-Level Positive COVID19 Testing Results

## Additional Abstracts and Links


[The mental health and behavioral consequences of terrorism](http://hdl.handle.net/10022/AC:P:9338)
Charles J. DiMaggio; Sandro Galea (J Emergency Med 2008 August; 35(2):  139-47)
The behavioral consequences of terrorist incidents have received considerable recent attention, much of it driven by the 1995 Oklahoma City bombings and the attacks of September 11, 2001 in the United States. In this chapter we will review the available evidence about the mental health and behavioral consequences of terrorism, consider methodological and research issues that challenge the field, and discuss the evidence for specific prevention and treatment efforts aimed at mitigating the mental health and behavioral consequences of terrorism.

[The behavioral consequences of terrorism: a meta-analysis](http://hdl.handle.net/10022/AC:P:9325)
Charles J. DiMaggio; Sandro Galea (Academic Emergency Med 2006; 13(5): 559-566.)
Terrorism is an ongoing concern throughout the world. The United States Department of State documented 228 acts of worldwide terrorism between 1961 and 2003. Of these 197 were in the developing world. In the US, attention has turned to the threat of terrorism with the September 11, 2001 terrorist bombings, the largest single-day loss of human-life in US history since the Civil War. Subsequent terrorist attacks such as the October 12, 2002 Bali nightclub bombings, the March 11, 2004 Madrid train bombings, and the July 7, 2005 London bombings, have further brought the threat of terrorism to the forefront of national and international discourse. Several large-scale reviews of the consequences of disasters have been published. These reviews have documented the prevalence and correlates of specific psychiatric disorders and behaviors after mass events. Post-traumatic stress disorder (PTSD) emerges from this work as the best studied, and likely most common, psychopathology after disasters. One theme to arise from these reviews is that disasters that are caused by human-intent (such as terrorism) may be associated with a particularly high risk of psychopathology in their aftermath. As such, explicit study of the mental health consequences of terrorism may be warranted. To illuminate this issue, we undertook a review and synthesis of quantitative studies of the behavioral health effects of terrorist incidents focusing primarily on the prevalence and correlates of PTSD.


[Changes in Selective Serotonin Reuptake Inhibitor Prescription Rates Following a Terrorist Attack] http://hdl.handle.net/10022/AC:P:9335
Charles J. DiMaggio; Sandro Galea; Paula Madrid (Psychiatr Serv 2006; 57(11): 1656-1657.)


[Substance use and misuse in the aftermath of terrorism: A Bayesian meta-analysis](http://hdl.handle.net/10022/AC:P:13887)
Charles J. DiMaggio; Sandro Galea; Guohua Li (Addiction 2009; 104: 894-904.)
Aim To conduct a comprehensive analysis of the conflicting evidence on substance use and misuse following mass traumas such as terrorist incidents. Methods We reviewed and synthesized evidence from 31 population-based studies using Bayesian meta-analysis and meta-regression. Results The majority of the studied were conducted in the aftermath of the terrorist attacks of 11 September 2001. Controlling for exposure, type of incident and time since the event occurred, 7.3% [95% credible interval (CrI) 1.1–32.5%] of a population can be expected to report increased alcohol consumption in the first 2 years following a terrorist event. There is, however, a 20% probability that the prevalence will be as high as 14%. The unadjusted prevalence of increased cigarette smoking following a terrorist event is 6.8% (95% Cr I 2.6–16.5%). Unadjusted reports of mixed drug use (including narcotics and prescription medications) was 16.3% (95% Cr I 1.3–72.5%). Conclusions These results underscore the potentially pervasive behavioral health effects of mass terrorism, and suggest that public health interventions may usefully consider substance use as an area of focus after such events.



[Spatial proximity and the risk of psychopathology after a terrorist attack](http://hdl.handle.net/10022/AC:P:9334)
Charles J. DiMaggio; Sandro Galea; Michael Emch (Psychiatry Research, vol. 176, no. 1 (2010-03), pp. 55-61.)
Previous studies concerned with the relation of proximity to the September 11, 2001 terrorist attacks and subsequent psychopathology have produced conflicting results. The goals of this analysis are to assess the appropriateness of using Bayesian hierarchical spatial techniques to answer the question of the role of proximity to a mass trauma as a risk factor for psychopathology. Using a set of individual-level Medicaid data for New York State, and controlling for age, gender, median household income and employment-related exposures, we applied Bayesian hierarchical modeling methods for spatially aggregated data. We found that distance from the World Trade Center site in the post-attack time period was associated with increased risk of anxiety-related diagnoses. In the months following the attack, each 2-mile increment in distance closer to the World Trade Center site was associated with a 7% increase in anxiety-related diagnoses in the population. No similar association was found during a similar time period in the year prior to the attack. We conclude that spatial variables help more fully describe post-terrorism psychiatric risk and may help explain discrepancies in the existing literature about these attacks. These methods hold promise for the characterization of disease risk where spatial patterning of ecologic-level exposures and outcomes merits consideration.


[Bayesian hierarchical spatial modeling of substance abuse patterns following a mass trauma: the role of time and place](http://hdl.handle.net/10022/AC:P:9336)
Charles J. DiMaggio; Sandro Galea; David Vlahov (Subst Use Misuse 2009; 44(12): 1725-1743)
To illustrate how spatial modeling methods may provide insight about the relation between proximity to mass trauma and substance use, we examined the role of proximity to a terrorist event in determining risk of substance use-related diagnoses. Previous analyses that have assessed changes in substance use following mass traumas such as terrorist attacks have produced conflicting results. We used Bayesian hierarchical modeling methods to assess whether distance from the World Trade Center (WTC) site in the aftermath of the September 11, 2001 terrorist attacks was associated with risk of substance use-related diagnoses. In analyses controlling for age, gender, median household income and employment-related exposure to the terrorist attacks, we found that each two mile increment in distance away from the World Trade Center site was associated with 18% more substance use-related diagnoses in the population we studied; this relation between distance from the WTC and substance use-related disorder was the opposite of the relations observed one year before the same attacks in the same area. By accounting for spatial relationships that may influence the population risk of substance use health disorder, this approach helps explain some of the conflicting observations in the extant literature. These methods hold promise for the characterization of disease risk where spatial patterning of exposures and outcomes may matter.


[Population Psychiatric Medication Prescription Rates Following a Terrorist Attack](http://hdl.handle.net/10022/AC:P:9340)
Charles J. DiMaggio; Sandro Galea; Paula Madrid (Prehospital Disast Med. 2007; 22 (6):  479-484.)
Introduction: While several population-based studies have documented behavioral health disturbances following terrorist attacks, a number of mental health service utilization analyses published thus far have presented conflicting conclusions. Problem: Our purpose was to determine if mental health service utilization increased following a terrorist attack by assessing changes in psychoactive drug prescription rates. Methods: We measured the rate of selective serotonin reuptake inhibitor (SSRI) prescriptions among New York State Medicaid enrollees before and after the terrorist attacks of September 11, 2001, and assessed the association between geographic proximity to the events and changes in the rate of SSRI prescriptions around September 11, 2001 Results: From September to December 2001, among individuals residing within 3 miles of the WTC site, there was an 18.2% increase in the SSRI prescription rate compared to the previous 8 month period (p=0.0011). While there was a 9.3% increase for non-New York City residents, this change was not statistically significant (p=0.74). Conclusions: We conclude that there was a quantifiable increase in the dispensing of psychoactive drugs following the terrorist attacks of September 11, 2001 and that this effect varied in response to geographic proximity to the events. These findings build on the growing body of knowledge on the pervasive effects of disasters and terrorist events for population health and demonstrate the need to include mental and behavioral health as key components of surge capacity and public health response to mass traumas.


[Analyzing Postdisaster Surveillance Data: The Effect of the Statistical Method](http://hdl.handle.net/10022/AC:P:19291)
Charles J. DiMaggio; Sandro Galea; David M. Abramson (Disaster Med Public Health Preparedness. 2008 June; 2(2): 119-226)
Data from existing administrative databases and ongoing surveys or surveillance methods may prove indispensable after mass traumas as a way of providing information that may be useful to emergency planners and practitioners. The analytic approach, however, may affect exposure prevalence estimates and measures of association. We compare Bayesian hierarchical modeling methods to standard survey analytic techniques for survey data collected in the aftermath of a terrorist attack. Estimates for the prevalence of exposure to the terrorist attacks of September 11, 2001, varied by the method chosen. Bayesian hierarchical modeling returned the lowest estimate for exposure prevalence with a credible interval spanning nearly 3 times the range of the confidence intervals (CIs) associated with both unadjusted and survey procedures. Bayesian hierarchical modeling also returned a smaller point estimate for measures of association, although in this instance the credible interval was tighter than that obtained through survey procedures. Bayesian approaches allow a consideration of preexisting assumptions about survey data, and may offer potential advantages, particularly in the uncertain environment of postterrorism and disaster settings. Additional comparative analyses of existing data are necessary to guide our ability to use these techniques in future incidents.


[The Mental Health Consequences of Terrorism: Implications for Emergency Medicine Practitioners](http://hdl.handle.net/10022/AC:P:9331)
Charles J. DiMaggio; Paula Madrid; George T. Loo; Sandro Galea (Journal of Emergency Medicine, vol. 35, no. 2 (August 2008), pp. 139-147.)
Emergency physicians are likely to be first-line responders in any local or regional terrorist event. In addition to preparing for the potential physical conditions and injuries that are associated with terrorism, they should be aware of the behavioral and mental health implications as well. It is helpful to be familiar with the characteristics that predict who may be at increased risk for mental illness after such events and how they may be identified in an Emergency Department setting. Although most people in the general population with behavioral conditions stemming from a terrorist event can be expected to recover spontaneously within several months, other individuals are at increased risk of developing more debilitating mental health conditions that have been associated with post-terrorist and disaster environments. Screening tools are available to help emergency practitioners identify them and refer patients for more formal psychiatric evaluation and potential interventions to facilitate and speed the recovery process.


[Preparing for disasters: What should you know, and when should you know it?](http://hdl.handle.net/10022/AC:P:19939)
Charles J. DiMaggio; David Markenson; Irwin E. Redlener  (JAAPA. 2005 Mar; 18 (3): 40-48.)
Three waves of terrorism have ushered in a new era in public health, safety, and health care in the United States: The February 26, 1993 explosions at New York's World Trade Center, the April 19, 1995 bombing at the Murrah Federal Building in Oklahoma City, and the September 11, 2001 attacks, along with the anthrax cases that followed. Those events have awakened federal, state, and local governments to the urgency of improving their disaster-response capabilities. The health professions have also stepped forward to delineate the roles of their members in disasters, establish minimum competencies, and develop new training programs. Physician assistants have a strong tradition of responding to crisis. In all likelihood, PAs will be among the first responders to any disaster in the United States. It is incumbent on the profession and on individual PAs to understand what their roles would be in a disaster and to prepare accordingly.


[The Willingness of U.S. Emergency Medical Technicians to Respond to Terrorist Incidents](http://hdl.handle.net/10022/AC:P:15753)
David Markenson; Charles J. DiMaggio; Irwin E. Redlener (Biosecurity and Bioterrorism: Biodefense Strat Pract and Scien 2005; 3(4): 331-337.)
A nationally representative sample of basic and paramedic emergency medical service providers in the United States was surveyed to assess their willingness to respond to terrorist incidents. EMTs were appreciably (9-13%) less willing than able to respond to such potential terrorist-related incidents as smallpox outbreaks, chemical attacks, or radioactive dirty bombs (p < 0.0001). EMTs who had received terrorism-related continuing medical education within the previous 2 years were twice as likely (OR = 1.9, 95% CI 1.9, 2.0) to be willing to respond to a potential smallpox dissemination incident as those who indicated that they had not received such training. Timely and appropriate training, attention to interpersonal concerns, and instilling a sense of duty may increase first medical provider response rates.


[Comfort level of emergency medical service providers in responding to weapons of mass destruction events: impact of training and equipment](http://hdl.handle.net/10022/AC:P:15492)
Michael J. Reilly; David Markenson; Charles J. DiMaggio (Prehospital Disast Med 2007;22(4):297–303.)
Background: Numerous studies have suggested that emergency medical services (EMS) providers are ill-prepared in the areas of training and equipment for response to events due to weapons of mass destruction (WMD) and other public health emergencies (epidemics, etc.). Methods: A nationally representative sample of basic and paramedic EMS providers in the United States was surveyed to assess whether they had received training in WMD and/or public health emergencies as part of their initial provider training and as continuing medical education within the past 24 months. Providers also were surveyed as to whether their primary EMS agency had the necessary specialty equipment to respond to these specific events. Results: More than half of EMS providers had some training in WMD response. Hands-on training was associated with EMS provider comfort in responding to chemical, biological, and/or radiological events and public health emergencies (odds ratio (OR) = 3.2,95% confidence interval (CI) 3.1, 3.3). Only 18.1% of providers surveyed indicated that their agencies had the necessary equipment to respond to a WMD event. Emergency medical service providers who only received WMD training reported higher comfort levels than those who had equipment, but no training. Conclusions: Lack of training and education as well as the lack of necessary equipment to respond to WMD events is associated with decreased comfort among emergency medical services providers in responding to chemical, biological, and/or radiological incidents. Better training and access to appropriate equipment may increase provider comfort in responding to these types of incidents

[Preparing Health Professions Students for Terrorism, Disaster, and Public Health Emergencies: Core Competencies](http://hdl.handle.net/10022/AC:P:18771)
Irwin E. Redlener; Charles J. DiMaggio; David Markenson (Acad Med 2005; Jun 80 (6): 517-526.)
The recent increased threat of terrorism, coupled with the ever-present dangers posed by natural disasters and public health emergencies, clearly support the need to incorporate bioterrorism preparedness and emergency response material into the curricula of every health professions school in the nation. A main barrier to health care preparedness in this country is a lack of coordination across the spectrum of public health and health care communities and disciplines. Ensuring a unified and coordinated approach to preparedness requires that benchmarks and standards be consistent across health care disciplines and public health, with the most basic level being education of health professions students. Educational competencies establish the foundation that enables graduates to meet occupational competencies. However, educational needs for students differ from the needs of practitioners. In addition, there must be a clear connection between departments of public health and all other health care entities to ensure proper preparedness. The authors describe both a process and a list of core competencies for teaching emergency preparedness to students in the health care professions, developed in 2003 and 2004 by a team of experts from the four health professions schools of Columbia University in New York City. These competencies are directly applicable to medical, dental, nursing, and public health students. They can also easily be adapted to other health care disciplines, so long as differences in levels of proficiency and the need for clinical competency are taken into consideration.



[Public Health Department Training of Emergency Medical Technicians for Bioterrorism and Public Health Emergencies: Results of a National Assessment](http://hdl.handle.net/10022/AC:P:18772)
David Markenson; Michael J. Reilly; Charles J. DiMaggio (J Public Health Manag Pract 2005; 11(6 Suppl): S68-S74.)
Hypothesis: The public health system has a specialized body of knowledge and expertise in bioterrorism and public health emergency management that can assist in the development and delivery of continuing medical education programs to meet the needs of emergency medical service providers. Methods: A nationally representative sample of the basic and paramedic emergency medical service providers in the United States was surveyed to assess whether they had received training in weapons of mass destruction, bioterrorism, chemical terrorism, radiological terrorism, and/or public health emergencies, and how the training was provided. Results: Local health departments provided little in the way of training in biologic, chemical, or radiological terrorism to responders (7.4%- 14.9%). State health departments provided even less training (6.3%- 17.3%) on all topics to emergency medical services providers. Training that was provided by the health department in bioterrorism and public health emergency response was associated with responder comfort in responding to a bioterrorism event (OR = 2.74, 95% CI = 2.68, 2.81). Conclusions: Local and state public health agencies should work with the emergency medical services systems to develop and deliver training with an all-hazards approach

[Emergency Department Visits for Behavioral and Mental Health Care after a Terrorist Attack](http://hdl.handle.net/10022/AC:P:9328)
Charles J. DiMaggio; Sandro Galea; Lynne D. Richardson (Brain Injury August 2013;  27 (11), 1238-1243.)
To assess emergency department utilization by a population whose health care encounters can be tracked and quantified for behavioral and mental health conditions in the aftermath of the terrorist attacks of September 11, 2001. We assessed presentations to emergency departments using Medicaid analytic extract files for adult New York State residents for 2000 and 2001. We created four mutually exclusive geographic areas that were progressively more distant from the World Trade Center and divided data into 4 time periods. All persons in the files were categorized by their zip code of residence. We coded primary emergency department diagnoses for post traumatic stress disorder, substance abuse, psychogenic illness, severe psychiatric illness, depression, sleep disorders, eating disorders, stress-related disorders, and adjustment disorders. There was a 10.1% relative temporal increase in the rate of emergency department behavioral and mental health diagnoses following the September 11, 2001 terrorist attacks for adult Medicaid enrollees residing within a 3-mile radius of the World Trade Center site. Other geographic areas experienced relative declines. In population-based comparisons, Medicaid recipients, who lived within 3 miles of the World Trade Center following the September 11, 2001 terrorist attacks had a 20% increased risk of an emergency department mental health diagnosis (Prevalence Density Ratio 1.2, 95% CI 1.1, 1.3) compared to those who were non-New York City residents. The complex role that emergency departments may play in responding to terrorism and disasters is becoming increasingly apparent. To the best of our knowledge this is the first report of a quantifiable increase in emergency department utilization for mental health services by persons exposed to a terrorist attack in the United States.

[Partnership for Preparedness: A Model of Academic Public Health](http://hdl.handle.net/10022/AC:P:9333)
Charles J. DiMaggio; David Markenson; Kelly Henning; Irwin E. Redlener; Regina Zimmerman (J Public Health Manag Pract 2006; 12(1): 22-27.)
The New York City Department of Health and Mental Hygiene and the Columbia University Mailman School of Public Health's National Center for Disaster Preparedness undertook a collaborative project to establish a model academic health department. The goals were to increase student participation at the health department, increase faculty participation in health department activities, and facilitate health department faculty appointments at the school. As a result, 17 students were placed in full-time summer research projects designed by health department staff specifically for the project, 154 health department staff attended a series of six lectures presented by faculty, and five health department professionals applied for academic appointments at the school. The benefits of the efforts toward establishing an academic health department extend to all areas of public health practice, including those of preparedness.

[The Terrorists Attacks of September 11, 2001 in New York City](http://hdl.handle.net/10022/AC:P:9337)
Charles J. DiMaggio; Paula Madrid (Neria Y, Galea S and Norris F. Ed.  Mental Health Consequences of Disasters Ed. Cambridge University Press, 2013.)








