---
title: "Substance Use and Misuse"
---

# Substance Use and Misuse


[Applying Farr’s Law to project the drug overdose mortality epidemic in the United States](http://dx.doi.org/10.7916/D80000V7)
Salima Darakjy; Joanne Brady; Charles J. DiMaggio; Guohua Li (Inj. Epidemiol. (2014) 1: 31)
Unintentional drug overdose has increased markedly in the past two decades and surpassed motor vehicle crashes as the leading cause of injury mortality in many states. The purpose of this study was to understand the trajectory of the drug overdose epidemic in the United States by applying Farr’s Law. Farr’s “law of epidemics” and the Bregman-Langmuir back calculation method were applied to United States drug overdose mortality data for the years 1980 through 2011 to project the annual death rates from drug overdose from 2012 through 2035. From 1980–2011, annual drug overdose mortality increased from 2.7 to 13.2 deaths per 100,000 population. The projected drug overdose mortality would peak in 2016–2017 at 16.1 deaths per 100,000 population and then decline progressively until reaching 1.9 deaths per 100,000 population in 2035. The projected data based on Farr’s Law suggests that drug overdose mortality in the United States will decline in the coming years and return to the 1980 baseline level approximately by the year 2034.

[Effectiveness of bystander naloxone administration and overdose education programs: a meta-analysis](http://dx.doi.org/10.7916/D8RN37PD)
Rebecca E. Giglio; Guohua Li; Charles J. DiMaggio (Injury Epidemiology.  May 2015 2 (1): 2-10. )
The objective of this review was to assess the effectiveness of bystander naloxone administration and overdose education programs by synthesizing quantitative results reported in the research literature. Studies meeting predefined criteria were identified and reviewed, and their results were synthesized through meta-analysis. Odds ratios (ORs) and 95% confidence intervals (CIs) were calculated for overdose recoveries for individuals who received naloxone dispensed by non-medical community members, and the standardized mean difference was calculated for test scores of non-medical volunteers who received training in overdose management versus the scores of untrained volunteers. Pooled data from four studies showed that naloxone administration by bystanders was associated with a significantly increased odds of recovery compared with no naloxone administration (OR = 8.58, 95% CI = 3.90 to 13.25). Data from five studies of overdose education indicated that average scores were significantly higher for trained participants than untrained participants for tests on naloxone administration, overdose recognition, and overdose response (standardized mean difference = 1.35, 95% CI = 0.92 to 1.77). Empirical evidence in the research literature suggests that bystander naloxone administration and overdose education programs are associated with increased odds of recovery and with improved knowledge of overdose recognition and management in non-clinical settings.


[Spatial analytic approaches to explaining the trends and patterns of drug overdose deaths](http://hdl.handle.net/10022/AC:P:9339)
Charles J. DiMaggio; Angela Bucciarelli; Kenneth J. Tardiff; David Vlahov; Sandro Galea (Geography and Drug Addiction Ed Thomas Y, Richardson D and Cheung I.  Springer  New York 2009: pp 447-464.)
To effectively utilize and interpret spatial analyses, substance use researchers, public health practitioners and policy makers should be familiar with some of the available data analytic techniques, each of which comes with advantages and drawbacks. In this chapter we first discuss three cluster detection tools and their associated software applications. We then present a Bayesian hierarchical approach, briefly reviewing its theoretical underpinnings, commonly used models, and how inferences may be drawn a sample-based posterior distribution. We demonstrate the use of each approach on a set of substance abuse mortality data, comparing the results across the four tools. Our empiric illustration, considers the role of neighborhood-level socioeconomic status (SES) in explaining opiate-related overdose deaths in New York City. We end with a discussion of the implications of the choice of technique and software on interpreting spatial analyses of substance abuse and conclude that the choice of a method will be driven by the question to be answered, data and software availability and the intended audience or context in which the research is being conducted.


[Prescription drug monitoring and drug overdose mortality](http://dx.doi.org/10.7916/D8NP22K1)
Guohua Li; Joanne E. Brady; Barbara Lang; James F. Giglio; Hannah Wunsch; Charles J. DiMaggio (Public Health Reports. 2014;129:139–47.)
Background: Abuse of prescription drugs, particularly opioid analgesics, has become a major source of injury mortality and morbidity in the United States. To prevent the diversion and misuse of controlled substances, many states have implemented prescription drug monitoring programs (PDMPs). This study assessed the impact of state PDMPs on drug overdose mortality. Methods: We analyzed demographic and drug overdose mortality data for state-quarters with and without PDMPs in 50 states and the District of Columbia during 1999–2008, and estimated adjusted risk ratios (aRRs) and 95% confidence intervals (CIs) of drug overdose mortality associated with the implementation of state PDMPs through multivariable negative bionomial regression modeling. ResultsL During the study period, annual national death rates from drug overdose increased by 96%, from 5.7 deaths per 100,000 population in 1999 to 11.2 in 2008. The impact of PDMPs on drug overdose mortality varied greatly across states, ranging from a 35% decrease in Michigan (aRR=0.65; 95% CI=0.54–0.77) to a more than 3-fold increase in Nevada (aRR=3.37; 95% CI=2.48–4.59). Overall, implementation of PDMPs was associated with an 11% increase in drug overdose mortality (aRR=1.11; 95% CI=1.02–1.21). Conclusions: Implementation of PDMPs did not reduce drug overdose mortality in most states through 2008. Program enhancement that facilitates the access and use of prescription drug monitoring data systems by healthcare practitioners is needed.






